# Data Analysis using NumPy and Pandas

Numpy Array Operations:

Problem Statement: To learn how to use NumPy for creating arrays, performing basic
array operations, and conducting numerical computations through analyzing
temperature data.

Scenario: You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.

In [2]:
# Create a 1D NumPy Array:

import numpy as np

temperatures_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [5]:
# Inspection and Properties:

print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)

(7,)
float64
7


In [12]:
# Array Operations:

""" Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32 """

temperatures_f = (temperatures_w1 * 9/5) + 32
print(temperatures_f)

""" Find the maximum, minimum, and mean temperatures for the week."""

maximum_temp = np.max(temperatures_w1)
print("Maximum Temperature:", maximum_temp)

minimum_temp = np.min(temperatures_w1)
print("Minimum Temperature:", minimum_temp)

mean_temp = np.mean(temperatures_w1)
print("Mean Temperature:", round(mean_temp,2))

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.54


In [15]:
# Array Slicing and Indexing:

first_three_days = temperatures_w1[0:3]
print(first_three_days)

weekend = temperatures_w1[-2:]
print(weekend)

middle_three_days = temperatures_w1[2:5]
print(middle_three_days)

[22.5 25.3 20.8]
[24.8 21.9]
[20.8 23.4 26.1]


In [16]:
# Create a 2D Array:

import numpy as np
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [23]:
# Inspect and Slice the 2D Array:

print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)

week1 = temperatures[0]
print("Week 1:", week1)

week2 = temperatures[1]
print("Week 2:", week2)

weekends = temperatures[:, -2:]
print("Weekend temperatures:")
print(weekends)

(2, 7)
float64
14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend temperatures:
[[24.8 21.9]
 [22.8 20.1]]


Pandas Series:

In [58]:
# Creating Pandas Series:

import pandas as pd
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [59]:
# Indexing and Slicing:

""" integer index position"""
print(marks[0])

""" Use the loc"""
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

""" Use the iloc"""
print(marks.iloc[2])

""" Apply a boolean & retrieve the ranks where the
marks are greater than 90."""
print(marks > 90)
print(marks[marks > 90])

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1     True
Rank2     True
Rank3    False
Rank4    False
Rank5    False
dtype: bool
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_2522/1758882595.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [60]:
# Manipulating Series:

""" Modify the mark of the student with the 1st rank to 100."""

marks.loc['Rank1'] = 100
print(marks)

""" Remove the entry corresponding to the last rank from the Series."""

marks = marks.drop('Rank5')
print(marks)



Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [61]:
""" Compute the CGPA by dividing each mark in the Series by 10."""

cgpa = marks / 10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


Pandas DataFrame:

In [62]:
# Creating Pandas DataFrame:

import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [74]:
# Data Exploration:

"""Display the DataFrame"""
print(transactions)

"""Display the first 5 rows"""
print(transactions.head())

"""Display the last 5 rows"""
print(transactions.tail())

"""Display the shape of the DataFrame"""
print(transactions.shape)

"""Display the column names"""
print(transactions.columns)

"""Display the data types of each column"""
print(transactions.dtypes)

""" Display only the 'ProductCategory' and 'Amount' columns."""

print(transactions[['ProductCategory', 'Amount']])

""" Retrieve the last 3 columns of the DataFrame using iloc or loc."""

print(transactions.iloc[:, -3:])

""" Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200."""

filtered_data = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]
print(filtered_data)

""" Find the value counts for the 'ProductCategory' column."""

print(transactions['ProductCategory'].value_counts())

""" Find the unique values in the 'Region' column."""

print(transactions['Region'].unique())

""" Group by 'Region' and find the mean amount for each region."""

region_mean = transactions.groupby('Region')['Amount'].mean()
print(region_mean)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [78]:
# Manipulating the DataFrame:

""" Modify the 'Amount' for the transaction with TransactionID 102 to 165."""

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions[transactions['TransactionID'] == 102])

""" Add a new column 'Discount' by calculating 10% of the 'Amount'."""

transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

""" Remove the row with TransactionID 109."""

transactions = transactions.loc[transactions['TransactionID'] != 109]
print(transactions)

""" Delete the 'Discount' column from the DataFrame."""

transactions = transactions.drop('Discount', axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
1            102        Clothing  South     165      16.5
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            1